### PR TITLE
PhD Position in Vienna

### PR DESCRIPTION
**Pull request by perebor**
Hi Daniel,

I'd like to put up this advertisement for a PhD position in our group.

Best regards,
Friedrich

### CODE REVIEW

**Comment by satlive** [comment]
Friedrich, I am sorry, I did not get the email with that PR. I just noticed it today :(

**Comment by perebor** [comment]
No problem, the posting would anyway have coincided with lockdowns
everywhere. I'm going to update the call next week and make a new PR then.

Cheers,
Friedrich

Am Fr., 15. Mai 2020 um 18:56 Uhr schrieb satlive <notifications@github.com

**Comment by satlive** [comment]
Ok, good.

You can just keep this PR open and update the call. I will merge it then.

**Comment by satlive** [comment]
#63 is online. I am closing this one.

**Pull request closed without merging**
