### PR TITLE
Added SAT'15 registration announcement.

### PR DESCRIPTION
**Pull request by weaversa**

### CODE REVIEW

**Comment by Mystelven** [comment]
By seeing this new event, It would be interesting to make a link with : 

Deadline extended : http://www.satlive.org/2015/04/23/sat2015-cfp.html
First deadline : http://www.satlive.org/2015/04/03/sat2015-cfp.html

To have the "history" of one event, from the first call of papers until the real event.

**Comment by weaversa** [comment]
Is this something to put in the top 'layout' block?

**Comment by Mystelven** [comment]
Well, in fact this feature is not developped yet, I just thought it could be an idea. 

So I raised an issue for it, we will see what @satlive is thinking about it.

**Comment by satlive** [comment]
Nice idea, but I have no idea how to implement it in a simple way: it would require to have a "link" between the posts.

**Comment by Mystelven** [comment]
On the same principle as the clickable "tag". We should have a symbol "History". 
When we click on this symbol, (as on a tag page) we can see this history :).

**Comment by satlive** [comment]
Tags are a built-in feature in Jekyll. It simply works "out of the box". 

Maybe something like https://github.com/aleung/jekyll-post-revision would do the trick?

**Comment by Mystelven** [comment]
It's indeed a good idea to use this plugin.
 
Let's not reinvent the wheel :+1: !

**Pull request merged**
